project:
  type: website
  output-dir: docs/es

lang: es

website:
  navbar:
    left:
      - text: Información General
        href: about.qmd
      - text: Una guía paso a paso
        href: step_by_step_guide.qmd
      - text: ¡Ponte en contacto!
        href: get_in_touch.qmd
      - text: Recursos
        href: other_materials.qmd
        