---
title: "FOSSILPOL project"
---

This website presents all information needed about the FOSSILPOL workflow that aims to process and standardise global palaeoecological pollen data.

<br>

## Authors
The FOSSILPOL workflow has been developed during the ERC project called the “Humans on Planet Earth” (HOPE) team at the University of Bergen:
Suzette G.A. Flantua#, Ondrej Mottl#, Vivian Felde#, Kuber P. Bhatta#, Hilary Birks, John-Arvid Grytnes, Alistair Seddon, H. John B. Birks
# shared first authors

<br>

## Project sections

The project consists of several sections:

* **A guide to process and standardise global palaeoecological pollen datasets for large-scale synthesis** - An open-access manuscript in review in Global Ecology and Biogeography

* **[FOSSILPOL workflow](https://github.com/HOPE-UIB-BIO/FOSSILPOL-workflow)** - A tool to process multiple fossil pollen sequences to create a comprehensive, standardised dataset compilation, ready for multi-sequence and multi-proxy analyses (coded in the R environment)

* **[R-Fossilpol package](https://github.com/HOPE-UIB-BIO/R-Fossilpol-package)** - An R-package developed specifically to provide tools and functions for the FOSSILPOL workflow.

* **[Detailed guide to FOSSILPOL workflow](https://hope-uib-bio.github.io/FOSSILPOL-website/step_by_step_guide.html)** - A step-by-step guide for users of FOSSILPOL with description of the most important functions and user criteria throughout the workflow.

* **[Scandinavia example](https://github.com/HOPE-UIB-BIO/FOSSILPOL-example-Scandinavia)** - Example of the FOSSILPOL workflow applied to fossil pollen sequences in northen Europe

* **[Issue tracker](https://github.com/HOPE-UIB-BIO/FOSSILPOL-issues)** - Specific GitHub repository to manage all Issues detected in the FOSSILPOL workflow

* **[Future updates](https://github.com/orgs/HOPE-UIB-BIO/projects/3/views/1)** - Over of the future updates we plan to do on the FOSSILPOL workflow and package.

<br>

## Website pages

* [General information](about.html) - Information about how to obtain, set up, and run FOSSILPOL project

* [A step-by-step guide](step_by_step_guide.html) - Detailed information about individual steps of the data processing

* [Contribute](contributing.html) - Information about potential collaboration and issue reporting

* [Project future updates](road_map.html) - Information about updates to the software and project

<br>

## Versions
The version of the FOSSILPOL workflow: **0.0.1**

The version of the R-Fossilpol package: **0.0.1**

The version of the FOSSILPOL website: **0.0.1**


